services:
  - type: web
    name: push-message-api
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build --workspace backend
    startCommand: npm run start --workspace backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        sync: false
      - key: TOKEN_SECRET
        generateValue: true
      - key: YANDEX_CLOUD_NOTIFICATION_CHANNEL_ARN
        sync: false
      - key: YANDEX_CLOUD_STATIC_KEY_ID
        sync: false
      - key: YANDEX_CLOUD_STATIC_KEY_SECRET
        sync: false
      - key: YANDEX_CLOUD_VAPID_PUBLIC_KEY
        sync: false

  - type: web
    name: push-message-web
    runtime: static
    buildCommand: npm install --include=dev && npm run build --workspace frontend
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        sync: false